services:
  pig-mysql:
    build:
      context: docs/db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: bubble-mysql
    image: bubble-mysql
    ports:
      - 33306:3306
    networks:
      - spring_cloud_default

  bubble-redis:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    ports:
      - 36379:6379
    restart: always
    container_name: bubble-redis
    hostname: bubble-redis
    networks:
      - spring_cloud_default

  bubble-register:
    build:
      context: ./bubble-register
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
    environment:
      MYSQL_HOST: bubble-mysql
      REDIS_HOST: bubble-redis
    container_name: bubble-register
    hostname: bubble-register
    image: bubble-register
    networks:
      - spring_cloud_default

  bubble-gateway:
    build:
      context: ./bubble-gateway
    restart: always
    ports:
      - 9999:9999
    container_name: bubble-gateway
    hostname: bubble-gateway
    image: bubble-gateway
    environment:
      REDIS_HOST: bubble-redis
      NACOS_HOST: bubble-register
    networks:
      - spring_cloud_default

  bubble-auth:
    build:
      context: ./bubble-auth
    restart: always
    container_name: bubble-auth
    hostname: bubble-auth
    image: bubble-auth
    environment:
      REDIS_HOST: bubble-redis
      NACOS_HOST: bubble-register
    networks:
      - spring_cloud_default

  bubble-biz-backend:
    build:
      context: ./bubble-biz/bubble-biz-backend
    restart: always
    container_name: bubble-biz-backend
    hostname: bubble-biz-backend
    image: bubble-biz-backend
    environment:
      MYSQL_HOST: bubble-mysql
      REDIS_HOST: bubble-redis
      NACOS_HOST: bubble-register
    networks:
      - spring_cloud_default

  bubble-monitor:
    build:
      context: ./bubble-visual/bubble-monitor
    restart: always
    ports:
      - 5001:5001
    container_name: bubble-monitor
    hostname: bubble-monitor
    image: bubble-monitor
    environment:
      NACOS_HOST: bubble-register
    networks:
      - spring_cloud_default

  bubble-codegen:
    build:
      context: ./bubble-visual/bubble-codegen
    restart: always
    container_name: bubble-codegen
    hostname: bubble-codegen
    image: bubble-codegen
    environment:
      MYSQL_HOST: bubble-mysql
      REDIS_HOST: bubble-redis
      NACOS_HOST: bubble-register
    networks:
      - spring_cloud_default

  bubble-quartz:
    build:
      context: ./bubble-visual/bubble-quartz
    restart: always
    image: bubble-quartz
    container_name: bubble-quartz
    environment:
      MYSQL_HOST: bubble-mysql
      REDIS_HOST: bubble-redis
      NACOS_HOST: bubble-register
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name:  spring_cloud_default
    driver: bridge
